apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\d3x573\Path\kompose.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: rtuccep
  name: rtuccep
spec:
  ports:
    - name: "81"
      port: 81
      targetPort: 81
  selector:
    io.kompose.service: rtuccep
status:
  loadBalancer: {}
